export const NOREQUESTBODY = "No request body provided";
export const ZODERRORS = "Zod errors, invalid formats of request body"
export const DATABASEERRORS = "Issue talking to the database";
export const DUPLICATEUSERNAME = "Choose a different username"
export const DUPLICATEEMAIL = "Choose a different email"
export const SUCCESSFUL = "Successfully performed the task"
export const NOTFOUND = "Not found"
export const INCORRECTPASSWORD = "Password is not correct"
export const LOGINSUCCESSFUL = "Login Successful"
export const UNAUTHORIZED = "Unauthorized, Relogin"
export const PUBLICKEYNOTVERIFIED = "This public key is already registered but not verified yet, try verifying it if you are the owner of this public key"
export const PUBLICKEYTAKEN = "This public key is already registered and verified"
export const PUBLICKEYADDED = "New public key added to the database, now verify it"
export const PUBLICKEYVERIFICATIONFAILED = "Invalid signature"
